server:
  port: 8080

#datasource information
spring:
  datasource:
    url: jdbc:mysql://wallet_databse:3306/wallet_transfer_db?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#database configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect