spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/wallet_transfer_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234

  ## Hibernate Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update